import {
  Student,
  Staff,
  AttendanceRecord,
  FeePayment,
  FeeStructure,
  Exam,
  ExamMark,
  Supplier,
  PurchaseOrder,
  SalesItem,
  InventoryItem,
  BusRoute,
  Announcement,
  FinancialTransaction,
  SystemNotification,
  User,
} from '@/types';

export const currentUser: User = {
  id: 'usr-1',
  name: 'Dr. Rajesh Sharma',
  email: 'admin@absschool.edu.in',
  role: 'Super Admin',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  phone: '+91 98765 43210',
  status: 'Active',
  lastLogin: '2026-07-23 09:15 AM',
};

export const initialStudents: Student[] = [
  {
    id: 'std-101',
    admissionNo: 'ABS-2024-001',
    rollNo: '101',
    firstName: 'Aarav',
    lastName: 'Verma',
    name: 'Aarav Verma',
    className: '10th',
    section: 'A',
    dob: '2010-04-15',
    gender: 'Male',
    bloodGroup: 'O+',
    photo: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    fatherName: 'Suresh Verma',
    motherName: 'Sunita Verma',
    parentPhone: '+91 98111 22334',
    parentEmail: 'suresh.verma@example.com',
    address: '42, Park Avenue, Block C, New Delhi',
    busRoute: 'Route 4 - Dwarka Express',
    feeStatus: 'Paid',
    totalFees: 65000,
    paidFees: 65000,
    dueFees: 0,
    attendancePercent: 94.5,
    medicalInfo: 'No known allergies',
    joiningDate: '2020-04-01',
    status: 'Active',
  },
  {
    id: 'std-102',
    admissionNo: 'ABS-2024-002',
    rollNo: '102',
    firstName: 'Ananya',
    lastName: 'Sharma',
    name: 'Ananya Sharma',
    className: '10th',
    section: 'A',
    dob: '2010-08-22',
    gender: 'Female',
    bloodGroup: 'B+',
    photo: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    fatherName: 'Vikram Sharma',
    motherName: 'Meena Sharma',
    parentPhone: '+91 98222 33445',
    parentEmail: 'vikram.sharma@example.com',
    address: '15, Model Town, Sector 14',
    busRoute: 'Route 1 - Model Town Circuit',
    feeStatus: 'Partial',
    totalFees: 65000,
    paidFees: 40000,
    dueFees: 25000,
    attendancePercent: 98.0,
    joiningDate: '2019-04-01',
    status: 'Active',
  },
  {
    id: 'std-103',
    admissionNo: 'ABS-2024-003',
    rollNo: '103',
    firstName: 'Rohan',
    lastName: 'Gupta',
    name: 'Rohan Gupta',
    className: '12th',
    section: 'B',
    dob: '2008-01-10',
    gender: 'Male',
    bloodGroup: 'A+',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    fatherName: 'Anil Gupta',
    motherName: 'Rekha Gupta',
    parentPhone: '+91 98333 44556',
    parentEmail: 'anil.g@example.com',
    address: '88, Green Park Extension',
    busRoute: 'Route 2 - South Extension',
    feeStatus: 'Pending',
    totalFees: 82000,
    paidFees: 0,
    dueFees: 82000,
    attendancePercent: 88.2,
    joiningDate: '2016-04-01',
    status: 'Active',
  },
  {
    id: 'std-104',
    admissionNo: 'ABS-2024-004',
    rollNo: '104',
    firstName: 'Diya',
    lastName: 'Patel',
    name: 'Diya Patel',
    className: 'LKG',
    section: 'A',
    dob: '2022-05-18',
    gender: 'Female',
    bloodGroup: 'O-',
    photo: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    fatherName: 'Bhavesh Patel',
    motherName: 'Nisha Patel',
    parentPhone: '+91 98444 55667',
    parentEmail: 'b.patel@example.com',
    address: '102, Sunshine Apartments',
    busRoute: 'Route 1 - Model Town Circuit',
    feeStatus: 'Paid',
    totalFees: 45000,
    paidFees: 45000,
    dueFees: 0,
    attendancePercent: 96.0,
    joiningDate: '2024-04-01',
    status: 'Active',
  },
  {
    id: 'std-105',
    admissionNo: 'ABS-2024-005',
    rollNo: '105',
    firstName: 'Vivaan',
    lastName: 'Singh',
    name: 'Vivaan Singh',
    className: '5th',
    section: 'C',
    dob: '2015-11-05',
    gender: 'Male',
    bloodGroup: 'AB+',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    fatherName: 'Gurpreet Singh',
    motherName: 'Jasleen Kaur',
    parentPhone: '+91 98555 66778',
    parentEmail: 'singh.g@example.com',
    address: '24, Civil Lines, Near Bus Stand',
    feeStatus: 'Paid',
    totalFees: 52000,
    paidFees: 52000,
    dueFees: 0,
    attendancePercent: 92.4,
    joiningDate: '2021-04-01',
    status: 'Active',
  },
];

export const initialStaff: Staff[] = [
  {
    id: 'stf-201',
    empId: 'EMP-001',
    firstName: 'Mrs. Sunita',
    lastName: 'Rao',
    name: 'Mrs. Sunita Rao',
    role: 'Teacher',
    department: 'Science & Mathematics',
    designation: 'Senior PGT Physics',
    email: 'sunita.rao@absschool.edu.in',
    phone: '+91 97111 88990',
    joiningDate: '2015-06-15',
    qualification: 'M.Sc Physics, B.Ed',
    experienceYears: 12,
    salary: 68000,
    photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    status: 'Active',
    subjects: ['Physics', 'Science'],
    allocatedClass: '10th A',
  },
  {
    id: 'stf-202',
    empId: 'EMP-002',
    firstName: 'Mr. Amit',
    lastName: 'Tiwari',
    name: 'Mr. Amit Tiwari',
    role: 'Accountant',
    department: 'Finance & Accounts',
    designation: 'Chief Accountant',
    email: 'accounts@absschool.edu.in',
    phone: '+91 97222 88991',
    joiningDate: '2018-02-01',
    qualification: 'M.Com, Tally Certified',
    experienceYears: 8,
    salary: 54000,
    photo: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
    status: 'Active',
  },
  {
    id: 'stf-203',
    empId: 'EMP-003',
    firstName: 'Ramesh',
    lastName: 'Kumar',
    name: 'Ramesh Kumar',
    role: 'Transport Manager',
    department: 'Transport',
    designation: 'Head Driver / Fleet Incharge',
    email: 'transport@absschool.edu.in',
    phone: '+91 97333 88992',
    joiningDate: '2017-08-10',
    qualification: 'Heavy Transport License',
    experienceYears: 15,
    salary: 32000,
    photo: 'https://images.unsplash.com/photo-1547037579-f0fc020ac3be?w=150&auto=format&fit=crop&q=80',
    status: 'Active',
    busRouteHandled: 'Route 1 - Model Town Circuit',
  },
  {
    id: 'stf-204',
    empId: 'EMP-004',
    firstName: 'Priya',
    lastName: 'Deshmukh',
    name: 'Priya Deshmukh',
    role: 'Librarian',
    department: 'Academics',
    designation: 'Chief Librarian',
    email: 'library@absschool.edu.in',
    phone: '+91 97444 88993',
    joiningDate: '2021-07-01',
    qualification: 'M.Lib.I.Sc',
    experienceYears: 6,
    salary: 42000,
    photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    status: 'Active',
  },
];

export const initialFeePayments: FeePayment[] = [
  {
    id: 'pay-1',
    receiptNo: 'RCP-2026-0891',
    studentId: 'std-101',
    studentName: 'Aarav Verma',
    className: '10th',
    amount: 32500,
    paymentMode: 'UPI',
    paymentDate: '2026-07-20',
    feeCategory: 'Tuition',
    status: 'Success',
    collectedBy: 'Mr. Amit Tiwari',
  },
  {
    id: 'pay-2',
    receiptNo: 'RCP-2026-0892',
    studentId: 'std-102',
    studentName: 'Ananya Sharma',
    className: '10th',
    amount: 40000,
    paymentMode: 'Card',
    paymentDate: '2026-07-18',
    feeCategory: 'Tuition',
    status: 'Success',
    collectedBy: 'Mr. Amit Tiwari',
  },
  {
    id: 'pay-3',
    receiptNo: 'RCP-2026-0893',
    studentId: 'std-104',
    studentName: 'Diya Patel',
    className: 'LKG',
    amount: 45000,
    paymentMode: 'Bank Transfer',
    paymentDate: '2026-07-15',
    feeCategory: 'Tuition',
    status: 'Success',
    collectedBy: 'Reception desk',
  },
];

export const feeStructures: FeeStructure[] = [
  { id: 'fs-1', className: 'LKG', tuitionFee: 35000, admissionFee: 5000, transportFee: 8000, examFee: 2000, labFee: 0, totalAnnualFee: 50000, dueDate: '2026-08-10' },
  { id: 'fs-2', className: 'UKG', tuitionFee: 36000, admissionFee: 5000, transportFee: 8000, examFee: 2000, labFee: 0, totalAnnualFee: 51000, dueDate: '2026-08-10' },
  { id: 'fs-3', className: '5th', tuitionFee: 42000, admissionFee: 5000, transportFee: 10000, examFee: 3000, labFee: 2000, totalAnnualFee: 62000, dueDate: '2026-08-10' },
  { id: 'fs-4', className: '10th', tuitionFee: 50000, admissionFee: 5000, transportFee: 12000, examFee: 4000, labFee: 4000, totalAnnualFee: 75000, dueDate: '2026-08-10' },
  { id: 'fs-5', className: '12th', tuitionFee: 60000, admissionFee: 5000, transportFee: 14000, examFee: 5000, labFee: 6000, totalAnnualFee: 90000, dueDate: '2026-08-10' },
];

export const initialExams: Exam[] = [
  { id: 'ex-1', name: 'First Unit Test 2026', examType: 'Unit Test', className: '10th', startDate: '2026-08-05', endDate: '2026-08-12', totalMarks: 50, passingMarks: 18, status: 'Upcoming' },
  { id: 'ex-2', name: 'Mid Term Examinations 2026', examType: 'Mid Term', className: '12th', startDate: '2026-09-15', endDate: '2026-09-28', totalMarks: 100, passingMarks: 35, status: 'Upcoming' },
  { id: 'ex-3', name: 'Annual Evaluation 2026', examType: 'Annual', className: 'LKG', startDate: '2026-03-10', endDate: '2026-03-20', totalMarks: 100, passingMarks: 40, status: 'Completed' },
];

export const examMarks: ExamMark[] = [
  { id: 'm-1', examId: 'ex-3', examName: 'Annual Evaluation 2026', studentId: 'std-101', studentName: 'Aarav Verma', rollNo: '101', className: '10th', subject: 'Mathematics', marksObtained: 94, maxMarks: 100, grade: 'A1', remarks: 'Outstanding logical reasoning' },
  { id: 'm-2', examId: 'ex-3', examName: 'Annual Evaluation 2026', studentId: 'std-101', studentName: 'Aarav Verma', rollNo: '101', className: '10th', subject: 'Physics', marksObtained: 88, maxMarks: 100, grade: 'A2', remarks: 'Great practical performance' },
  { id: 'm-3', examId: 'ex-3', examName: 'Annual Evaluation 2026', studentId: 'std-102', studentName: 'Ananya Sharma', rollNo: '102', className: '10th', subject: 'Mathematics', marksObtained: 98, maxMarks: 100, grade: 'A1', remarks: 'Class topper in Mathematics' },
];

export const initialSuppliers: Supplier[] = [
  { id: 'sup-1', supplierCode: 'SUP-001', name: 'Raymond School Uniforms Pvt Ltd', companyName: 'Raymond Retail', contactPerson: 'Vikram Mehta', phone: '+91 99887 11223', email: 'v.mehta@raymond.com', gstNo: '07AAAAA0000A1Z5', category: 'Uniforms', outstandingBalance: 45000, address: 'Connaught Place, New Delhi', status: 'Active' },
  { id: 'sup-2', supplierCode: 'SUP-002', name: 'NCERT & S.Chand Publishers', companyName: 'S.Chand Publishing House', contactPerson: 'Rajesh Singhal', phone: '+91 99887 22334', email: 'orders@schand.com', gstNo: '07BBBBB1111B1Z2', category: 'Books & Stationery', outstandingBalance: 12000, address: 'Daryaganj, New Delhi', status: 'Active' },
  { id: 'sup-3', supplierCode: 'SUP-003', name: 'Dell India Educational Systems', companyName: 'Dell Technology Solutions', contactPerson: 'Neha Kapoor', phone: '+91 99887 33445', email: 'edu.sales@dell.com', gstNo: '07CCCCC2222C1Z9', category: 'Computers & IT', outstandingBalance: 0, address: 'Cyber City, Gurugram', status: 'Active' },
];

export const initialPurchases: PurchaseOrder[] = [
  { id: 'po-1', poNumber: 'PO-2026-041', supplierId: 'sup-1', supplierName: 'Raymond School Uniforms Pvt Ltd', orderDate: '2026-07-05', deliveryDate: '2026-07-15', totalAmount: 185000, status: 'Goods Received', itemsCount: 450 },
  { id: 'po-2', poNumber: 'PO-2026-042', supplierId: 'sup-2', supplierName: 'NCERT & S.Chand Publishers', orderDate: '2026-07-12', deliveryDate: '2026-07-25', totalAmount: 94000, status: 'Sent', itemsCount: 600 },
];

export const initialSales: SalesItem[] = [
  { id: 'sl-1', invoiceNo: 'INV-2026-1021', customerName: 'Aarav Verma', customerType: 'Student', itemCategory: 'Uniform', itemName: 'Summer Blazer & Trousers Set (Size 36)', quantity: 1, unitPrice: 2800, totalAmount: 2800, discount: 100, netAmount: 2700, date: '2026-07-21', paymentMethod: 'UPI' },
  { id: 'sl-2', invoiceNo: 'INV-2026-1022', customerName: 'Diya Patel', customerType: 'Student', itemCategory: 'ID Card', itemName: 'Smart RFID Student ID Card with Lanyard', quantity: 1, unitPrice: 350, totalAmount: 350, discount: 0, netAmount: 350, date: '2026-07-22', paymentMethod: 'Cash' },
  { id: 'sl-3', invoiceNo: 'INV-2026-1023', customerName: 'Ananya Sharma', customerType: 'Student', itemCategory: 'Books', itemName: 'Grade 10 Science & Math Reference Kit', quantity: 1, unitPrice: 1450, totalAmount: 1450, discount: 50, netAmount: 1400, date: '2026-07-23', paymentMethod: 'Card' },
];

export const initialInventory: InventoryItem[] = [
  { id: 'inv-1', itemCode: 'UNIF-BLAZER-M', name: 'Boys Navy Blue Blazer (Medium)', category: 'Uniforms', quantityInStock: 85, minReorderLevel: 20, unitPrice: 2200, supplierName: 'Raymond School Uniforms', warehouseLocation: 'Store Room A1', status: 'In Stock' },
  { id: 'inv-2', itemCode: 'UNIF-TIE-LOG', name: 'ABS Crest School Tie', category: 'Uniforms', quantityInStock: 12, minReorderLevel: 30, unitPrice: 180, supplierName: 'Raymond School Uniforms', warehouseLocation: 'Store Room A2', status: 'Low Stock' },
  { id: 'inv-3', itemCode: 'STAT-NOTE-100P', name: 'ABS Customized Notebook 100 Pages', category: 'Stationery', quantityInStock: 450, minReorderLevel: 100, unitPrice: 65, supplierName: 'NCERT & S.Chand Publishers', warehouseLocation: 'Store Room B1', status: 'In Stock' },
  { id: 'inv-4', itemCode: 'COMP-DELL-I5', name: 'Dell OptiPlex Desktop Core i5', category: 'Computers', quantityInStock: 35, minReorderLevel: 5, unitPrice: 48000, supplierName: 'Dell India Educational', warehouseLocation: 'Computer Lab 2', status: 'In Stock' },
];

export const initialBuses: BusRoute[] = [
  { id: 'bus-1', routeNo: 'Route 1', routeName: 'Model Town - Pitampura Express', busNo: 'DL-01-AB-1234', driverName: 'Ramesh Kumar', driverPhone: '+91 97333 88992', conductorName: 'Mukesh Chand', capacity: 42, assignedStudentsCount: 38, feePerTerm: 8000, status: 'Operational' },
  { id: 'bus-2', routeNo: 'Route 2', routeName: 'South Extension - Green Park', busNo: 'DL-01-AB-5678', driverName: 'Sanjay Yadav', driverPhone: '+91 97333 99881', conductorName: 'Suresh Pal', capacity: 42, assignedStudentsCount: 40, feePerTerm: 9500, status: 'Operational' },
  { id: 'bus-3', routeNo: 'Route 4', routeName: 'Dwarka Sector 10 Circuit', busNo: 'DL-01-AB-9012', driverName: 'Harminder Singh', driverPhone: '+91 97333 77665', conductorName: 'Baldev Singh', capacity: 52, assignedStudentsCount: 49, feePerTerm: 11000, status: 'Operational' },
];

export const initialAnnouncements: Announcement[] = [
  { id: 'ann-1', title: 'Independence Day Flag Hoisting & Cultural Programme', content: 'All students from standard 5th to 12th must report in full white uniform by 7:30 AM on 15th August.', targetAudience: ['Students', 'Parents', 'Teachers', 'Staff'], priority: 'Important', author: 'Principal Office', date: '2026-07-22', status: 'Published' },
  { id: 'ann-2', title: 'Submission of Term 1 Examination Syllabus', content: 'Teachers are requested to upload the finalized Unit Test 1 syllabus on the portal before 30th July.', targetAudience: ['Teachers'], priority: 'Normal', author: 'Vice Principal', date: '2026-07-20', status: 'Published' },
  { id: 'ann-3', title: 'Urgent: Transport Fee Clearance Reminder', content: 'Parents with pending bus fee installments for Q2 are requested to clear dues to avoid service disruption.', targetAudience: ['Parents'], priority: 'Urgent', author: 'Accounts Department', date: '2026-07-23', status: 'Published' },
];

export const initialFinancials: FinancialTransaction[] = [
  { id: 'tx-1', transactionNo: 'TXN-8801', type: 'Income', category: 'School Fees', amount: 32500, date: '2026-07-20', description: 'Tuition Fee collection for Aarav Verma', paymentMode: 'UPI', approvedBy: 'Mr. Amit Tiwari' },
  { id: 'tx-2', transactionNo: 'TXN-8802', type: 'Expense', category: 'Salary', amount: 480000, date: '2026-07-01', description: 'Staff Salary Disbursement for June 2026', paymentMode: 'Bank Transfer', approvedBy: 'Dr. Rajesh Sharma' },
  { id: 'tx-3', transactionNo: 'TXN-8803', type: 'Income', category: 'Uniform Sales', amount: 14500, date: '2026-07-21', description: 'Counter uniform & kit sales', paymentMode: 'Cash', approvedBy: 'Mr. Amit Tiwari' },
  { id: 'tx-4', transactionNo: 'TXN-8804', type: 'Expense', category: 'Electricity', amount: 62000, date: '2026-07-10', description: 'Monthly electricity bill for Main Campus & Labs', paymentMode: 'Bank Transfer', approvedBy: 'Dr. Rajesh Sharma' },
];

export const initialNotifications: SystemNotification[] = [
  { id: 'nt-1', title: 'Low Stock Alert: ABS Crest School Tie', message: 'Current stock is 12 units (Below reorder threshold of 30).', type: 'warning', timestamp: '10 mins ago', read: false, category: 'Inventory' },
  { id: 'nt-2', title: 'New Fee Payment Received', message: 'Receipt #RCP-2026-0891 of ₹32,500 recorded for Aarav Verma.', type: 'success', timestamp: '1 hour ago', read: false, category: 'Fee Due' },
  { id: 'nt-3', title: 'Upcoming Exam Schedule Finalized', message: 'First Unit Test 2026 timetable published for Class 10th.', type: 'info', timestamp: '3 hours ago', read: true, category: 'Exam' },
  { id: 'nt-4', title: 'Driver Attendance Flag', message: 'Bus Route 2 driver checked in 15 mins late today.', type: 'error', timestamp: '5 hours ago', read: true, category: 'Attendance' },
];
